services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - CAMINHO PARA O/DirTrein:/app/DirTrein               
      - CAMINHO PARA O/training_errors.log:/app/training_errors.log  
      - CAMINHO PARA O/trainingXgboost.pkl:/app/trainingXgboost.pkl
    environment:
      FLASK_APP: __FinalXgboostPyMuPDF.py
      FLASK_ENV: development